from pathlib import Path

migration = Path('docs/ui/UI_MIGRATION.md')
text = migration.read_text()
text = text.replace(
    '7. A reservation is the concurrency slot. Every unreleased, unexpired reservation for the owner counts toward the active limit. Successful submission binds the reservation to the returned RenderLab job UUID. Immediate submission failure releases the concurrency slot but leaves the reservation row/admission timestamp intact so the admitted attempt still counts against the rolling 60-minute limit.\n8. Terminal job observation (`succeeded|failed|cancelled`) releases the bound reservation through the shared poll path. Poll-time worker failover/reassignment is continuation of the same admitted job and must not create a second reservation or increment the hourly count.\n9. An unbound reservation expires after a bounded conservative TTL if the process dies between reserve and bind/release. Bound reservations are normally released on terminal poll and retain a conservative safety expiry so a permanently unobserved completion cannot lock the account forever. Expiry is a safety valve, not a second rate-limit window.\n',
    '7. A reservation is the provisional concurrency slot. Every unreleased, unexpired **unbound** reservation counts toward the active limit. Successful submission binds the reservation to the returned RenderLab job UUID. Immediate submission failure releases the provisional slot but leaves the reservation row/admission timestamp intact so the admitted attempt still counts against the rolling 60-minute limit.\n8. Once bound, current owner-scoped `generation_jobs` state is the active-slot authority inside the transactional admission check: `queued|preparing|running|persisting` remains active; `succeeded|failed|cancelled` no longer consumes a slot. A bound reservation whose job is missing/unreadable remains conservative until its bounded lease expires rather than allowing unbounded parallel spend. Poll-time worker failover/reassignment is continuation of the same admitted job and must not create a second reservation or increment the hourly count.\n9. An unbound reservation expires after a bounded conservative TTL if the process dies between reserve and bind/release. Bound reservations retain a conservative safety expiry for missing/unreadable-job recovery. Expiry is a safety valve, not a second rate-limit window, and ordinary terminal-slot release must not depend on the browser polling at exactly the right moment.\n'
)
text = text.replace(
    'Verify signed-out `401`; missing/suspended access `403`; global disabled and per-account disabled `503`; default one-active limit and account active-limit override; default 12-admitted rolling-hour limit and account hourly override; expiry/release behavior; immediate-failure release with hourly count preserved; successful bind; terminal-poll release; and malformed/unavailable-input attempts not consuming admission.',
    'Verify signed-out `401`; missing/suspended access `403`; global disabled and per-account disabled `503`; default one-active limit and account active-limit override; default 12-admitted rolling-hour limit and account hourly override; expiry/release behavior; immediate-failure release with hourly count preserved; successful bind; terminal-job state releasing the slot without poll-timing dependence; missing/unreadable bound jobs remaining conservative until expiry; and malformed/unavailable-input attempts not consuming admission.'
)
trailing = '''- Bound reservations use current `generation_jobs` state for active-slot release; a missing/unreadable job stays conservative until bounded lease expiry rather than allowing unbounded parallel spend.
- The configured external backend path may remain enabled only if RenderLab obtains the reservation before making the external network request. Provider/backend code cannot be the only place enforcing the limit.
- No billing/credit ledger is inferred from these counters. Admin labels must say limits/guardrails, not credits or plan allowance.
'''
if trailing not in text:
    raise SystemExit('trailing UI-051 10C clauses not found')
text = text.replace(trailing, '')
migration.write_text(text)

frontend = Path('docs/architecture/FRONTEND_ARCHITECTURE.md')
text = frontend.read_text()
text = text.replace(
    '`generation_admission_reservations` is the temporary concurrency authority: an unreleased/unexpired reservation occupies a slot before backend dispatch; successful submission binds the reservation to the returned RenderLab job UUID; terminal status observed through the existing poll boundary releases the slot. Immediate submission failure releases concurrency but the immutable admission timestamp still counts in the rolling-hour abuse window. Poll-time failover is continuation of the same admitted job and never reserves again. Crashed/unbound work expires conservatively, and bound work has a safety expiry so missing terminal observation cannot create a permanent lock. These are abuse/spend guardrails, not billing credits.',
    '`generation_admission_reservations` is the transactional pre-dispatch concurrency authority: an unreleased/unexpired unbound reservation occupies a slot before backend dispatch; successful submission binds the reservation to the returned RenderLab job UUID. Once bound, current owner-scoped `generation_jobs` state is the slot authority—active lifecycle states keep the slot occupied while terminal state releases it for future admission. A missing/unreadable bound job remains conservative until bounded lease expiry. Immediate submission failure releases concurrency but the immutable admission timestamp still counts in the rolling-hour abuse window. Poll-time failover is continuation of the same admitted job and never reserves again. These are abuse/spend guardrails, not billing credits.'
)
frontend.write_text(text)
