from pathlib import Path


def replace(path: str, old: str, new: str) -> None:
    p = Path(path)
    text = p.read_text()
    if old not in text:
        raise SystemExit(f"missing expected text in {path}: {old[:180]!r}")
    p.write_text(text.replace(old, new, 1))

replace(
    "PROJECT.md",
    "- Workstream #215 is the immediate P0 account/security slice under `docs/architecture/ACCOUNT_SETTINGS_CAPABILITY_ROADMAP.md` and `docs/architecture/AUTH_EMAIL_SECURITY_HARDENING_IMPLEMENTATION_CONTRACT.md`.",
    "- Workstream #215 is implementation-complete in the repository for both #215A and #215B and is awaiting only the final #215B production rollout plus tracker/document closure. The governing records remain `docs/architecture/ACCOUNT_SETTINGS_CAPABILITY_ROADMAP.md` and `docs/architecture/AUTH_EMAIL_SECURITY_HARDENING_IMPLEMENTATION_CONTRACT.md`.",
)
replace(
    "PROJECT.md",
    "- Security Advisor shows no new findings. Supabase still reports `auth_leaked_password_protection` because the organization is on Free, but the user has explicitly rejected upgrading Supabase solely for that feature. #215B is now the free RenderLab-owned compromised-password-screening slice using Have I Been Pwned Pwned Passwords k-anonymity; after that control is verified, the native Supabase warning is an accepted platform limitation rather than a roadmap blocker. CAPTCHA remains evaluated/deferred. Hosted policy and production presentation are synchronized at the 15-character minimum; post-cutover Vercel checks found no runtime-error clusters and no error/fatal logs for the new deployment.",
    "- The paid Supabase leaked-password path was permanently rejected. Contract amendment PR #249 merged as `31824147c7e3716ddf187a260220c74733102fbe`, replacing that plan gate with free RenderLab-owned HIBP Pwned Passwords k-anonymity screening.\n- #215B implementation PR #250 exact head `15edffab3662c28c5169584b8982e5df2831c880` passed all six attached workflows: UI Shell `34868699614`, Compromised Password Screening `34868698510`, Brand / Launch `34868698354`, Integrated Release `34868698377`, Account Identity `34868698376`, and Engineering Quality `34868698449`. Account Identity artifact `10357573841` has digest `sha256:bc22e9ed81a4e7ef30b82329236c3580c7b6f61d4ced42c47f988741c6f5fad8`.\n- PR #250 merged as `f3f89d0859154b2ab45b5364ce1acb04a0eb204b`. The two workflows GitHub attached to merged `main` both passed: Engineering Quality `34869098474` and UI Shell `34869098397`. The free HIBP control is therefore repository-implemented, exact-head verified, merged and merged-main verified.\n- Security Advisor shows no new findings. The native `auth_leaked_password_protection` warning remains intentionally visible on Supabase Free and is now an accepted platform limitation rather than a roadmap blocker. The known server-owned `rls_enabled_no_policy` informational notices remain expected.\n- #215B is **not yet production-live**. Production remains exact source `27eda7ed0a619435b9d89531bdeb3fffe772e803` / READY deployment `dpl_6yCKG1TvPLRZLusxVJG2ALrA5YT7`. The user authorized the final rollout, but execution was interrupted before a deployment workflow or new Vercel deployment was created. Automatic Git → Vercel deployment remains disabled.",
)

replace(
    "docs/architecture/ACCOUNT_SETTINGS_CAPABILITY_ROADMAP.md",
    "**Status:** ACCEPTED PLANNING BASELINE / MERGED / IMPLEMENTATION ACTIVE",
    "**Status:** ACCEPTED PLANNING BASELINE / #215 REPOSITORY IMPLEMENTATION COMPLETE / #215B PRODUCTION ROLLOUT PENDING",
)
replace(
    "docs/architecture/ACCOUNT_SETTINGS_CAPABILITY_ROADMAP.md",
    "**Current execution:** #215A current-plan hardening is complete, verified and production-live: repository policy merged as `8ea859df84f5173267defbf3e278a95bba403014`, hosted Auth minimum is 15, security notifications/templates are branded, configured acceptance passed, and exact application source `27eda7ed0a619435b9d89531bdeb3fffe772e803` is live as Vercel deployment `dpl_6yCKG1TvPLRZLusxVJG2ALrA5YT7`. The user permanently rejected upgrading Supabase solely for leaked-password protection; #215B is redefined as free RenderLab-owned compromised-password screening through the Have I Been Pwned Pwned Passwords k-anonymity API.",
    "**Current execution:** #215A current-plan hardening is complete, verified and production-live. The user permanently rejected upgrading Supabase solely for leaked-password protection. #215B was redefined as free RenderLab-owned compromised-password screening through the Have I Been Pwned Pwned Passwords k-anonymity API, contracted in PR #249 / `31824147c7e3716ddf187a260220c74733102fbe`, implemented on PR #250 exact head `15edffab3662c28c5169584b8982e5df2831c880`, and merged as `f3f89d0859154b2ab45b5364ce1acb04a0eb204b`. All six exact-head workflows passed and merged-main Engineering `34869098474` plus UI Shell `34869098397` passed. #215B is not yet deployed; production remains source `27eda7ed0a619435b9d89531bdeb3fffe772e803` / deployment `dpl_6yCKG1TvPLRZLusxVJG2ALrA5YT7` until the authorized guarded rollout is completed.",
)
replace(
    "docs/architecture/ACCOUNT_SETTINGS_CAPABILITY_ROADMAP.md",
    "A fresh Security Advisor read after #215A hosted execution on 2026-09-14 still reports **Leaked Password Protection Disabled** as the only warning. The other current findings are the expected `rls_enabled_no_policy` informational notices for deliberately server-owned RenderLab tables. The current organization remains on Free. On 2026-09-14 the user explicitly rejected a Supabase plan upgrade solely for this control, so the warning is no longer a billing/plan gate. #215B instead owns free application-layer compromised-password screening; after that is verified, the Supabase-native warning remains visible as an accepted platform limitation and must not be misrepresented as cleared.",
    "A fresh Security Advisor read after #215B repository verification on 2026-09-14 still reports **Leaked Password Protection Disabled** as the only warning. The other current findings are the expected `rls_enabled_no_policy` informational notices for deliberately server-owned RenderLab tables. The organization remains on Free and the user explicitly rejected a Supabase upgrade solely for this feature. #215B free application-layer HIBP screening is now implemented and verified, so the native warning is an accepted platform limitation and must not be misrepresented as cleared. The final remaining #215 step is the authorized production rollout and closure record.",
)

replace(
    "docs/architecture/AUTH_EMAIL_SECURITY_HARDENING_IMPLEMENTATION_CONTRACT.md",
    "**Status:** #215A CURRENT-PLAN HARDENING COMPLETE + VERIFIED + PRODUCTION-LIVE / #215B FREE COMPROMISED-PASSWORD SCREENING CONTRACTED / SUPABASE PAID UPGRADE REJECTED",
    "**Status:** #215A COMPLETE + VERIFIED + PRODUCTION-LIVE / #215B IMPLEMENTED + EXACT-HEAD VERIFIED + MERGED + MERGED-MAIN VERIFIED / #215B PRODUCTION ROLLOUT PENDING / SUPABASE PAID UPGRADE REJECTED",
)
replace(
    "docs/architecture/AUTH_EMAIL_SECURITY_HARDENING_IMPLEMENTATION_CONTRACT.md",
    "#215A is therefore **implementation-complete, verified and production-live for the current Free plan**. #215 remains open only for #215B free compromised-password screening. No Supabase billing/plan decision remains in this workstream. Hosted policy and production application presentation are synchronized on the canonical 15-character minimum.",
    "#215A is therefore **implementation-complete, verified and production-live for the current Free plan**. #215B repository implementation is also complete, exact-head verified, merged and merged-main verified. The tracker remains open only for the final #215B production rollout plus documentation/issue closure. No Supabase billing/plan decision remains in this workstream. Hosted policy and the currently deployed application remain synchronized on the canonical 15-character minimum.",
)
replace(
    "docs/architecture/AUTH_EMAIL_SECURITY_HARDENING_IMPLEMENTATION_CONTRACT.md",
    "Hosted Auth and the production application are therefore synchronized on the canonical 15-character password-creation/replacement policy. #215A is complete for the current Free plan. #215B now proceeds only as the free RenderLab-owned HIBP compromised-password-screening slice; no Supabase plan upgrade will be pursued for this feature.\n\n## 3. Binding product/security decisions",
    "Hosted Auth and the production application are therefore synchronized on the canonical 15-character password-creation/replacement policy. #215A is complete for the current Free plan. No Supabase plan upgrade will be pursued for leaked-password protection.\n\n### Stage 4 #215B free compromised-password screening — repository implementation complete / production rollout pending — 2026-09-14\n\n- The user permanently rejected upgrading Supabase solely for leaked-password protection. Contract amendment PR #249 merged as `31824147c7e3716ddf187a260220c74733102fbe`, replacing the former Pro+ gate with the free RenderLab-owned HIBP Pwned Passwords range-API control.\n- Implementation PR #250 exact head `15edffab3662c28c5169584b8982e5df2831c880` added browser Web Crypto hashing, five-character-prefix k-anonymity, `Add-Padding: true`, local suffix comparison, submit-only lookup, bounded retry/fail-closed handling, deterministic Account Identity coverage, and an independent no-secret live HIBP reachability workflow.\n- All six exact-head workflows passed: UI Shell `34868699614`, Compromised Password Screening `34868698510`, Brand / Launch `34868698354`, Integrated Release `34868698377`, Account Identity `34868698376`, and Engineering Quality `34868698449`.\n- Account Identity artifact `10357573841` has digest `sha256:bc22e9ed81a4e7ef30b82329236c3580c7b6f61d4ced42c47f988741c6f5fad8`. The verifier proved no HIBP request occurs while typing; submit sends only the expected five-character prefix with no password/full-hash request data; known-compromised passwords are rejected; unavailable lookup retries once then fails closed; safe ordinary and recovery password changes preserve all existing recovery/session/revocation guarantees.\n- PR #250 merged as `f3f89d0859154b2ab45b5364ce1acb04a0eb204b`. The only two workflows GitHub attached to merged `main` both passed: Engineering Quality `34869098474` and UI Shell `34869098397`.\n- Post-merge Security Advisor showed no new findings. `auth_leaked_password_protection` remains intentionally visible because Supabase-native enforcement is disabled on Free; it is an accepted platform limitation, not unfinished RenderLab work. The existing server-owned `rls_enabled_no_policy` INFO notices remain expected.\n- This Stage 4 repository implementation is **not yet deployed**. Production remains source `27eda7ed0a619435b9d89531bdeb3fffe772e803` / READY Vercel deployment `dpl_6yCKG1TvPLRZLusxVJG2ALrA5YT7`. The user authorized the final rollout, but execution was interrupted before a deployment workflow or new Vercel deployment was created. Automatic Git → Vercel deployment remains disabled.\n\n## 3. Binding product/security decisions",
)

replace(
    "docs/architecture/INFRASTRUCTURE.md",
    "- Security Advisor will therefore continue to report `auth_leaked_password_protection`. After #215B is verified, that warning is an accepted Supabase-platform limitation rather than a RenderLab broader-beta blocker.",
    "- Security Advisor continues to report `auth_leaked_password_protection`. #215B is now verified in the repository, so that warning is an accepted Supabase-platform limitation rather than a RenderLab broader-beta blocker; it must not be presented as cleared.",
)
replace(
    "docs/architecture/INFRASTRUCTURE.md",
    "- No Supabase plan/billing change, schema/RLS change, new secret, paid HIBP subscription, R2 change or generation infrastructure change is authorized by this decision.\n\n## Security Rules",
    "- No Supabase plan/billing change, schema/RLS change, new secret, paid HIBP subscription, R2 change or generation infrastructure change is authorized by this decision.\n\n### #215B repository implementation verification — 2026-09-14\n\n- Contract amendment PR #249 merged as `31824147c7e3716ddf187a260220c74733102fbe`.\n- Implementation PR #250 exact head `15edffab3662c28c5169584b8982e5df2831c880` passed Engineering Quality `34868698449`, Account Identity `34868698376`, Compromised Password Screening `34868698510`, Integrated Release `34868698377`, UI Shell `34868699614`, and Brand / Launch `34868698354`.\n- The no-secret live HIBP workflow proved the official free range API reachable with a padded k-anonymity response. Account Identity artifact `10357573841` (`sha256:bc22e9ed81a4e7ef30b82329236c3580c7b6f61d4ced42c47f988741c6f5fad8`) verified submit-only lookup, prefix-only disclosure, compromised rejection, unavailable fail-closed retry, safe ordinary/recovery mutation, and preservation of existing session/revocation semantics.\n- PR #250 merged as `f3f89d0859154b2ab45b5364ce1acb04a0eb204b`; merged-main Engineering `34869098474` and UI Shell `34869098397` both passed.\n- Fresh Security Advisor showed no new findings. The native leaked-password warning remains accepted by design; the expected server-owned RLS/no-policy informational notices are unchanged.\n- The #215B application change is **not deployed yet**. Current production remains exact source `27eda7ed0a619435b9d89531bdeb3fffe772e803` / READY deployment `dpl_6yCKG1TvPLRZLusxVJG2ALrA5YT7`. A final guarded rollout is authorized but was not executed before this handoff. Automatic Git → Vercel deployment remains disabled.\n\n## Security Rules",
)

print("#215B handoff docs patched")
