from pathlib import Path


def replace(path: str, old: str, new: str):
    p = Path(path)
    text = p.read_text()
    if old not in text:
        raise SystemExit(f"missing expected text in {path}: {old[:160]!r}")
    p.write_text(text.replace(old, new, 1))

form = "src/features/account/account-password-form.tsx"
replace(
    form,
    'import { createBrowserSupabaseClient } from "@/lib/supabase/browser";\n',
    'import {\n  COMPROMISED_PASSWORD_MESSAGE,\n  PASSWORD_SAFETY_UNAVAILABLE_MESSAGE,\n  screenRenderLabCompromisedPassword,\n} from "./compromised-password-screening";\nimport { createBrowserSupabaseClient } from "@/lib/supabase/browser";\n',
)
replace(
    form,
    '      if (!recoveryMode) {\n        const { error: reauthenticationError } = await supabase.auth.signInWithPassword({\n',
    '      const screening = await screenRenderLabCompromisedPassword(newPassword);\n      if (screening === "compromised") {\n        setFeedback({ kind: "error", message: COMPROMISED_PASSWORD_MESSAGE });\n        return;\n      }\n      if (screening === "unavailable") {\n        setFeedback({ kind: "error", message: PASSWORD_SAFETY_UNAVAILABLE_MESSAGE });\n        return;\n      }\n\n      if (!recoveryMode) {\n        const { error: reauthenticationError } = await supabase.auth.signInWithPassword({\n',
)

verifier = "scripts/verify-account-identity.mjs"
replace(
    verifier,
    'const belowPolicyPassword = "TooShort-123!";\n',
    'const belowPolicyPassword = "TooShort-123!";\nconst compromisedPassword = "passwordpassword";\n',
)

helper_anchor = '''function assert(condition, message) {\n  if (!condition) throw new Error(message);\n}\n'''
helper_addition = helper_anchor + '''\nasync function mockPwnedPasswordLookup(page, passwordValue, mode) {\n  const hash = createHash("sha1").update(passwordValue, "utf8").digest("hex").toUpperCase();\n  const prefix = hash.slice(0, 5);\n  const suffix = hash.slice(5);\n  const routePattern = "https://api.pwnedpasswords.com/**";\n  let getCount = 0;\n\n  const handler = async (route) => {\n    const request = route.request();\n    if (request.method() === "OPTIONS") {\n      await route.fulfill({\n        status: 204,\n        headers: {\n          "access-control-allow-origin": "*",\n          "access-control-allow-methods": "GET, OPTIONS",\n          "access-control-allow-headers": "add-padding",\n        },\n      });\n      return;\n    }\n\n    assert(request.method() === "GET", `Pwned Passwords lookup used unexpected method ${request.method()}.`);\n    const url = new URL(request.url());\n    assert(url.pathname === `/range/${prefix}`, "Pwned Passwords lookup must send only the five-character SHA-1 prefix.");\n    assert(request.headers()["add-padding"] === "true", "Pwned Passwords lookup must request padded responses.");\n    assert(request.postData() == null, "Pwned Passwords lookup must not send a request body.");\n    assert(!request.url().includes(passwordValue), "Pwned Passwords lookup URL exposed the candidate password.");\n    assert(!request.url().includes(hash), "Pwned Passwords lookup URL exposed the complete password hash.");\n    getCount += 1;\n\n    if (mode === "unavailable") {\n      await route.abort("failed");\n      return;\n    }\n\n    const fillerSuffix = suffix === "0".repeat(35) ? "1".repeat(35) : "0".repeat(35);\n    const body = mode === "compromised"\n      ? `${suffix}:42\\r\\n${fillerSuffix}:0\\r\\n`\n      : `${fillerSuffix}:0\\r\\n`;\n    await route.fulfill({\n      status: 200,\n      headers: {\n        "access-control-allow-origin": "*",\n        "content-type": "text/plain; charset=utf-8",\n      },\n      body,\n    });\n  };\n\n  await page.route(routePattern, handler);\n  return {\n    getCount: () => getCount,\n    remove: () => page.unroute(routePattern, handler),\n  };\n}\n'''
replace(verifier, helper_anchor, helper_addition)

old_ordinary = '''  await page.getByLabel("Current password").fill(password);\n  await page.getByLabel("New password", { exact: true }).fill(belowPolicyPassword);\n  await page.getByLabel("Confirm new password", { exact: true }).fill(belowPolicyPassword);\n  assert(\n    await page.getByRole("button", { name: "Update password", exact: true }).isDisabled(),\n    "Below-policy password must remain client-blocked before Auth mutation.",\n  );\n  await page.getByLabel("New password", { exact: true }).fill(changedPassword);\n  await page.getByLabel("Confirm new password", { exact: true }).fill(changedPassword);\n  await page.getByRole("button", { name: "Update password", exact: true }).click();\n  await page.getByText("Password updated.", { exact: true }).waitFor({ state: "visible", timeout: 30_000 });\n'''
new_ordinary = '''  await page.getByLabel("Current password").fill(password);\n  await page.getByLabel("New password", { exact: true }).fill(belowPolicyPassword);\n  await page.getByLabel("Confirm new password", { exact: true }).fill(belowPolicyPassword);\n  assert(\n    await page.getByRole("button", { name: "Update password", exact: true }).isDisabled(),\n    "Below-policy password must remain client-blocked before Auth mutation.",\n  );\n\n  const compromisedLookup = await mockPwnedPasswordLookup(page, compromisedPassword, "compromised");\n  await page.getByLabel("New password", { exact: true }).fill(compromisedPassword);\n  await page.getByLabel("Confirm new password", { exact: true }).fill(compromisedPassword);\n  await page.waitForTimeout(100);\n  assert(compromisedLookup.getCount() === 0, "Compromised-password lookup must not run incrementally while typing.");\n  await page.getByRole("button", { name: "Update password", exact: true }).click();\n  await page.getByText("This password has appeared in known data breaches. Choose a different password.", { exact: true }).waitFor({ state: "visible", timeout: 10_000 });\n  assert(compromisedLookup.getCount() === 1, `Compromised-password submit expected one range GET, got ${compromisedLookup.getCount()}.`);\n  await compromisedLookup.remove();\n\n  const unavailableLookup = await mockPwnedPasswordLookup(page, changedPassword, "unavailable");\n  await page.getByLabel("New password", { exact: true }).fill(changedPassword);\n  await page.getByLabel("Confirm new password", { exact: true }).fill(changedPassword);\n  await page.getByRole("button", { name: "Update password", exact: true }).click();\n  await page.getByText("Password safety check is unavailable. Try again.", { exact: true }).waitFor({ state: "visible", timeout: 15_000 });\n  assert(unavailableLookup.getCount() === 2, `Unavailable password-safety check should retry once then fail closed; got ${unavailableLookup.getCount()} GETs.`);\n  await unavailableLookup.remove();\n\n  const safeChangeLookup = await mockPwnedPasswordLookup(page, changedPassword, "safe");\n  await page.getByRole("button", { name: "Update password", exact: true }).click();\n  await page.getByText("Password updated.", { exact: true }).waitFor({ state: "visible", timeout: 30_000 });\n  assert(safeChangeLookup.getCount() === 1, `Safe ordinary password change expected one range GET, got ${safeChangeLookup.getCount()}.`);\n  await safeChangeLookup.remove();\n'''
replace(verifier, old_ordinary, new_ordinary)

old_recovery = '''  await recoveryPage.getByLabel("New password", { exact: true }).fill(recoveredPassword);\n  await recoveryPage.getByLabel("Confirm new password", { exact: true }).fill(recoveredPassword);\n  await recoveryPage.getByRole("button", { name: "Update password", exact: true }).click();\n  await recoveryPage.getByText("Password updated.", { exact: true }).waitFor({ state: "visible", timeout: 30_000 });\n'''
new_recovery = '''  const safeRecoveryLookup = await mockPwnedPasswordLookup(recoveryPage, recoveredPassword, "safe");\n  await recoveryPage.getByLabel("New password", { exact: true }).fill(recoveredPassword);\n  await recoveryPage.getByLabel("Confirm new password", { exact: true }).fill(recoveredPassword);\n  await recoveryPage.getByRole("button", { name: "Update password", exact: true }).click();\n  await recoveryPage.getByText("Password updated.", { exact: true }).waitFor({ state: "visible", timeout: 30_000 });\n  assert(safeRecoveryLookup.getCount() === 1, `Safe recovery password change expected one range GET, got ${safeRecoveryLookup.getCount()}.`);\n  await safeRecoveryLookup.remove();\n'''
replace(verifier, old_recovery, new_recovery)

print("#215B free compromised-password implementation patched")
