from pathlib import Path

# UI migration tracker: record the branch candidate without pretending it is merged/live.
p = Path('docs/ui/UI_MIGRATION.md')
text = p.read_text()
marker = '**Landing production status: `APPROVED / PRODUCTION-LIVE`.**\n'
section = '''**Landing production status: `APPROVED / PRODUCTION-LIVE`.**\n\n## Phase 23 — Create Clear Composer v0.5 candidate — 2026-09-11\n- [x] User-approved Clear Composer v0.5 R&D direction recorded at `703bc5dbcc8e3b6a9236f08a8a62a87238e59bed`; isolated R&D PR #183 closed unmerged intentionally.\n- [x] Production implementation is tracked by issue #184 and draft PR #185 on `work/phase-23-create-clear-composer`; no schema, provider/worker, routing, auth/admission, ownership, storage or deployment contract is changed.\n- [x] Production Create now promotes Image/Video intent, labelled Add reference / Start image semantics, Primary/Reference/Start roles, dominant prompt, visible Advanced and stable Generate while preserving existing durable upload/generation/continuation behavior.\n- [x] Truthful generation and media-first result composition use the Landing-derived Lab Matrix language; ordinary controls remain conventional and native video playback keeps real controls.\n- [x] Human review of exact-head `a44146bf8e51f165b01e348b7c21621207edfc9e` evidence confirmed desktop/390px/reduced-motion authoring fidelity and the corrected 390px result actions remain above the fixed mobile dock.\n- [x] Exact-head `a44146b...` Engineering Quality `34622973715`, Create Clear Composer Visual `34622973510` and Create Lifecycle Visual `34622973690` passed; visual artifact `10272409290` digest `sha256:119887f24e8b9e82c9a143d64ea0ed04432657d6af8d45ae9f65a7d6dd0c53ac`, lifecycle artifact `10273068411` digest `sha256:939765825c24e4aa976a318e203785356a2e05c90f6a9b0bc4e5ac7178797a87`.\n- [x] Five remaining `a44146b...` failures were audited as stale pre-Clear-Composer presentation assertions or contract whitespace, not product behavior; correction commit `6e9cb6409ce9029e903f0330e099bbcb83bcbc1f` aligns those verifiers while preserving their substantive product invariants.\n- [ ] Final documentation-complete exact-head workflow matrix must pass before merge acceptance.\n- [ ] Merge to `main` remains separately explicit. Production deployment remains separately explicit and automatic Git → Vercel deployment stays disabled.\n\n**Phase 23 status: `VERIFIED IMPLEMENTATION CANDIDATE / FINAL EXACT-HEAD MATRIX PENDING / NOT MERGED / NOT DEPLOYED`.**\n'''
if marker not in text:
    raise SystemExit('UI_MIGRATION landing status marker not found')
p.write_text(text.replace(marker, section, 1))

# Durable UI decision: the user-approved interaction grammar is now the accepted Create direction.
p = Path('docs/ui/UI_DECISIONS.md')
text = p.read_text().rstrip() + '\n\n'
if '### UI-073 — Clear Composer keeps Create familiar while expression belongs to media' not in text:
    text += '''### UI-073 — Clear Composer keeps Create familiar while expression belongs to media\n**Status:** Accepted\n**Decision:** Create uses one stable Clear Composer grammar: obvious Image/Video intent, labelled reference or Start image semantics, explicit attached-media roles, dominant prompt, visible essential settings and Advanced disclosure, and one stable conventional Generate action. Generation/result expression belongs primarily to truthful media-stage and result composition; ordinary authoring controls stay stationary and understandable. Continuation keeps the stable `Create an image` / `Create a video` workspace heading and communicates Edit/Animate context through `Primary image` / `Reference image` / `Start image` roles rather than changing the whole screen title.\n**Reason:** Approved v0.5 R&D showed that familiar creative-tool grammar produces substantially better first-use clarity than abstract/orbital workspaces while the Landing-derived Lab Matrix visual language can still give RenderLab a distinctive authored identity.\n**Consequences:** Create must preserve current product/API/security/data contracts, maintained control semantics and real video controls. Image result continuation remains capability-derived; Animate binds the durable image as Video Start image. Generating state must be truthful and cannot invent progress, ETA, queue/provider stages or workflow mechanics. 390px and reduced-motion states must reach the same usable result, and result actions must remain clear of fixed shell navigation. Do not reintroduce giant abstract stages, hidden essential actions, 3D/orbital controls, generic SaaS glass-card nesting or a second animation runtime without a new explicit decision.\n**Evidence:** user-approved design record `design/rd/create-usability-first-v05.md`; implementation contract `docs/ui/CREATE_CLEAR_COMPOSER_IMPLEMENTATION_CONTRACT.md`; draft PR #185. Exact-head `a44146bf8e51f165b01e348b7c21621207edfc9e` passed Engineering Quality `34622973715`, Create Clear Composer Visual `34622973510` and configured Create Lifecycle `34622973690`; the final documentation-complete exact-head matrix remains required before merge.\n'''
p.write_text(text)

# Screen registry: production baseline remains current until merge, but record the verified replacement candidate accurately.
p = Path('docs/ui/SCREEN_REGISTRY.md')
text = p.read_text()
marker = '**Design artifacts:** `design/penpot/create-v0.2-desktop.svg`, `design/penpot/create-v0.2-mobile.svg`, `design/penpot/create-v0.2-runtime-states.svg`, `design/penpot/create-v0.3-advanced.svg`\n'
replacement = marker + '**Phase 23 design authority:** `design/rd/create-usability-first-v05.md`, `docs/ui/CREATE_CLEAR_COMPOSER_IMPLEMENTATION_CONTRACT.md`; draft PR #185 is a verified pre-merge production candidate and is not yet the `main`/production surface.\n'
if marker not in text:
    raise SystemExit('SCREEN_REGISTRY Create design marker not found')
text = text.replace(marker, replacement, 1)
marker2 = '**Do not change:** Do not turn Create into a generic ComfyUI form, expose worker/provider/R2 implementation or add fake runtime behavior.\n'
addition = '''**Phase 23 / UI-073 verified candidate:** The approved Clear Composer keeps one stable `Create an image` / `Create a video` workspace heading, promotes the maintained Image/Video choice, labels Add reference / Start image, names attached roles Primary image / Reference image / Start image, keeps prompt and Generate visually dominant, and places truthful generation/media-first result composition above the persistent composer. The production candidate retains existing model/aspect/video/Advanced controls, durable upload identity, `@imageN` aliases, one-source Video/two-source Image limits, native video playback and capability-derived continuation. Landing-derived 64px Lab Matrix registration, cool/warm atmosphere, precise rules and quarter-arc media framing are Create-owned presentation; depth remains media-only. On 390px, stage/result context compacts and continuation actions stay above the fixed mobile dock. Exact-head `a44146bf8e51f165b01e348b7c21621207edfc9e` passed Engineering Quality `34622973715`, Clear Composer Visual `34622973510` and configured Create Lifecycle `34622973690`; final documentation-complete matrix is still pending, so the current `main` Create remains the production authority until merge.\n\n'''
if marker2 not in text:
    raise SystemExit('SCREEN_REGISTRY Create do-not-change marker not found')
text = text.replace(marker2, addition + marker2, 1)
p.write_text(text)

# Component catalog: record the real component evolution without creating a competing component.
p = Path('docs/ui/COMPONENT_CATALOG.md')
text = p.read_text()
marker = '**Phase 7A premium interaction evidence:**'
note = '''**Phase 23 / UI-073 Clear Composer candidate:** `CreateWorkspace` remains the single authoritative Create surface; no parallel workspace or generic composer primitive was introduced. The production candidate promotes the maintained Image/Video ToggleGroup, labelled durable reference/Start-image action, explicit media roles, dominant prompt, conventional essential settings/Advanced/Generate, truthful generation stage and media-first durable result. It keeps existing state/functions for upload, polling, persistence, aliases and continuation, and continues to use Motion for React only for bounded Create-owned layout/media transitions with reduced-motion equivalence. Result-stage styling is scoped to Create in `globals.css`; ordinary controls do not parallax. Exact-head `a44146bf8e51f165b01e348b7c21621207edfc9e` passed Engineering Quality `34622973715`, Clear Composer Visual `34622973510` and Create Lifecycle `34622973690`; final docs-complete matrix is required before merge.\n\n'''
if marker not in text:
    raise SystemExit('COMPONENT_CATALOG phase marker not found')
text = text.replace(marker, note + marker, 1)
p.write_text(text)

# Implementation contract: move from in-progress to verified candidate, but keep final exact-head gate and merge/deploy boundaries explicit.
p = Path('docs/ui/CREATE_CLEAR_COMPOSER_IMPLEMENTATION_CONTRACT.md')
text = p.read_text()
text = text.replace('**Status:** IMPLEMENTATION IN PROGRESS / MERGE NOT AUTHORIZED', '**Status:** VERIFIED IMPLEMENTATION CANDIDATE / FINAL EXACT-HEAD MATRIX PENDING / MERGE NOT AUTHORIZED', 1)
marker = '## Documentation requirements\n'
record = '''## Verified implementation record before final documentation matrix\n\nThe production candidate has been implemented and human-reviewed without changing the product/backend boundary described above. Evidence already verified on exact head `a44146bf8e51f165b01e348b7c21621207edfc9e` includes:\n\n- Engineering Quality `34622973715` — PASS;\n- Create Clear Composer Visual `34622973510` — PASS; artifact `10272409290`, digest `sha256:119887f24e8b9e82c9a143d64ea0ed04432657d6af8d45ae9f65a7d6dd0c53ac`;\n- configured Create Lifecycle Visual `34622973690` — PASS; artifact `10273068411`, digest `sha256:939765825c24e4aa976a318e203785356a2e05c90f6a9b0bc4e5ac7178797a87`;\n- Account Ownership `34622973515`, Creative Iteration `34622974023` and Activity Cancel Visual `34622973514` — PASS.\n\nHuman evidence review confirmed the approved desktop/390px/reduced-motion authoring hierarchy, truthful active/result composition, media-first result framing and the Phase 23 mobile correction that keeps Image result continuation actions above the fixed mobile dock.\n\nFive other workflows on that head were audited rather than waived. Generation Admission stopped on trailing whitespace in this contract; UI Shell, Create Durable Upload, Library Lifecycle and Integrated Release reached their relevant application behavior but still asserted superseded pre-Clear-Composer heading/copy. Commit `6e9cb6409ce9029e903f0330e099bbcb83bcbc1f` removes the whitespace and updates only those stale presentation assertions to UI-073 semantics while retaining URL, output, durable identity, upload, ownership, generation, persistence, reference and continuation invariants. A final documentation-complete exact-head matrix is therefore still mandatory before merge acceptance.\n\n'''
if marker not in text:
    raise SystemExit('implementation contract documentation marker not found')
text = text.replace(marker, record + marker, 1)
p.write_text(text)
