from pathlib import Path


def replace_once(path: str, old: str, new: str) -> None:
    p = Path(path)
    text = p.read_text()
    count = text.count(old)
    if count != 1:
        raise SystemExit(f"{path}: expected exactly one match, found {count}: {old[:120]!r}")
    p.write_text(text.replace(old, new, 1))


phase25_project = """## Phase 25 Media Viewer Register + Source Fold — implementation closure — 2026-09-12
- The user-approved **Media Register + Source Fold v0.2** is the binding Viewer design authority: R&D issue #196, exact design head `639aef25e57e166be8d8b3d226b3e83930e05a25`, run `34703774288`, artifact `10300577421` (`sha256:06cade2dc2e9ce51dc871971530fa9641a7c1ef0cc0271e19763fcebfa8ca2b0`). UI-076 and `docs/ui/MEDIA_VIEWER_REGISTER_FOLD_IMPLEMENTATION_CONTRACT.md` governed the implementation slice; the contract merged in PR #199 as `a5db944acdefad7b9fcbbedd9d6b521b5a28c576`.
- PR #200 implemented the registered media-first Viewer, attached continuation register, local Prompt/Details/Manage disclosures, Favorite/Download quick actions, Manage-owned Collections/Rename/Delete, Result-primary Source Fold, narrow Result→Source stacking, reduced-motion equivalence and bounded image-only fine-pointer depth while preserving native video, continuation, recipe, Upscale, ownership, durable-media and action contracts. The definitive exact implementation head is `3e468ad0abd4f7b6645e86e298ce53a3a8ecf034`.
- The complete exact-head acceptance record passed: Engineering Quality `34717466149`, Library Search `34717466145`, Media Download `34717466273`, Library Favorites `34717466126`, Library History `34717466189`, Library Collections `34717466254`, Media Rename `34717466210`, Account Ownership `34717466209`, UI Shell `34717466157`, Media Delete `34717466203`, Library Lifecycle `34717466215`, Upscale Viewer `34717466198`, Media Viewer Register Fold `34717466185`, Library Batch Delete `34717466200`, Creative Iteration `34717466236`, Image Upscale Integration `34717466222`, Brand / Launch `34717466191`, Integrated Release `34717466228`, and fresh same-head Library Drag Drop `34718085004`. Early Brand / Integrated Release / Drag Drop cancellations were shared-resource concurrency noise; the unchanged isolated/fresh same-head runs above completed successfully.
- Final implementation evidence from Media Viewer Register Fold run `34717466185` is artifact `10304951419` (`sha256:d551006acffa260e8bbd83e25c2b156204a4391f1f9b1abcfc4e58aa0cc28e04`). Human review of the exact-head desktop, 390px, disclosure, Source Fold t000/t060/t180/t360, narrow comparison and reduced-motion captures found no fidelity drift from the approved v0.2 direction.
- PR #200 squash-merged to `main` as `b672c711f885092c5e92c42824078e7bd5bc691e`. GitHub attached exactly six push workflows to that merge SHA and all six passed: Creative Iteration `34718303019`, Media Viewer Register Fold Visual `34718302986`, Engineering Quality `34718303036`, Upscale Viewer Visual `34718303044`, Image Upscale Integration `34718302998`, and UI Shell Validation `34718302987`.
- Phase 25 is therefore user-approved, exact-head verified, merged and merged-main verified. No schema/API/provider/worker/R2/auth/admission/ownership/capability/routing contract changed. Production remains unchanged at source `0173c4c5ba08360b6352331118abc81978cfa774` / READY deployment `dpl_3Smw21pn4PPQ1DzN7aaWmTuuf991`; automatic Git → Vercel deployment remains disabled and no Phase 25 deployment is authorized.

"""
replace_once('PROJECT.md', '## UI/UX redesign program — continuation roadmap — 2026-09-12\n', phase25_project + '## UI/UX redesign program — continuation roadmap — 2026-09-12\n')
replace_once('PROJECT.md', '**Status: ACTIVE — Landing, Create and Library completed; remaining product surfaces still require redesign.**', '**Status: ACTIVE — Landing, Create, Library and Media Viewer completed; remaining product surfaces still require redesign.**')
replace_once('PROJECT.md', 'Phase 24 closed the approved Library Gallery Rail slice; it did **not** close the broader RenderLab UI/UX redesign program.', 'Phase 25 closed the approved Media Viewer Register + Source Fold slice; it did **not** close the broader RenderLab UI/UX redesign program.')
replace_once('PROJECT.md', '- **Library:** approved Gallery Rail v0.3 / UI-075, merged and verified, not yet deployed.\n- **Application shell:**', '- **Library:** approved Gallery Rail v0.3 / UI-075, merged and verified, not yet deployed.\n- **Media Viewer:** approved Media Register + Source Fold v0.2 / UI-076, merged and merged-main verified, not yet deployed.\n- **Application shell:**')
replace_once('PROJECT.md', '1. **Phase 25 — Media Viewer:** ACTIVE R&D in issue #196. Extend Gallery Rail media-object continuity into a cinematic inspection/continuation workspace while preserving all current Viewer product/security/capability contracts. Viewer remains a 3/4-expressiveness surface.\n2. **Phase 26 — Activity:** roadmap only until Phase 25 evidence closes. Bring real generation lifecycle/history states into the same authored system at 2/4 expressiveness without weakening Retry / Run Again / Cancel truth or operational clarity.', '1. **Phase 25 — Media Viewer:** COMPLETE / VERIFIED / MERGED / NOT DEPLOYED. UI-076 Media Register + Source Fold v0.2 is the repository-authoritative Viewer composition.\n2. **Phase 26 — Activity:** NEXT R&D SLICE. Bring real generation lifecycle/history states into the same authored system at 2/4 expressiveness without weakening Retry / Run Again / Cancel truth or operational clarity. No production implementation is authorized until Activity R&D is explicitly approved and an implementation contract is merged.')
replace_once('PROJECT.md', 'Only the immediate Phase 25 R&D slice may be expanded now; later phases remain roadmap-level until predecessor evidence exists.', 'Only the immediate Phase 26 Activity R&D slice may be expanded now; later phases remain roadmap-level until predecessor evidence exists.')
replace_once('PROJECT.md', '- The verified repository application baseline is Phase 24 / PR #194 merge `af88b93dcb4fcbca502b42f9ea1186192af48a6a`; Gallery Rail v0.3 is user-approved, exact-head verified and merged-main verified. Production remains the separately approved source `0173c4c5ba08360b6352331118abc81978cfa774`; no production deployment followed the Phase 24 repository merge.', '- The verified repository application baseline is Phase 25 / PR #200 merge `b672c711f885092c5e92c42824078e7bd5bc691e`; Media Register + Source Fold v0.2 / UI-076 is user-approved, exact-head verified and merged-main verified. Production remains the separately approved source `0173c4c5ba08360b6352331118abc81978cfa774`; no production deployment followed the Phase 25 repository merge.')

phase25_migration = """## Phase 25 — Media Viewer Register + Source Fold closure — 2026-09-12
**Status: `USER-APPROVED / EXACT-HEAD VERIFIED / MERGED / MERGED-MAIN VERIFIED / NOT DEPLOYED`.**

- [x] User-approved design authority: issue #196, exact R&D head `639aef25e57e166be8d8b3d226b3e83930e05a25`, run `34703774288`, artifact `10300577421`, digest `sha256:06cade2dc2e9ce51dc871971530fa9641a7c1ef0cc0271e19763fcebfa8ca2b0`.
- [x] UI-076 implementation contract merged before production code in PR #199 / `a5db944acdefad7b9fcbbedd9d6b521b5a28c576`.
- [x] PR #200 implemented the registered media-first Viewer, attached continuation register, local Prompt/Details/Manage disclosures, Favorite/Download quick actions, Manage-owned Collections/Rename/Delete, Result-primary Source Fold, narrow Result→Source stacking, reduced-motion equivalence and bounded image-only pointer depth without changing product/backend/security/data contracts.
- [x] Definitive exact implementation head `3e468ad0abd4f7b6645e86e298ce53a3a8ecf034` passed Engineering `34717466149`, Search `34717466145`, Download `34717466273`, Favorites `34717466126`, History `34717466189`, Collections `34717466254`, Rename `34717466210`, Ownership `34717466209`, Shell `34717466157`, Media Delete `34717466203`, Lifecycle `34717466215`, Upscale Viewer `34717466198`, Viewer Register Fold `34717466185`, Batch Delete `34717466200`, Creative Iteration `34717466236`, Image Upscale `34717466222`, Brand / Launch `34717466191`, Integrated Release `34717466228`, and fresh same-head Drag Drop `34718085004`.
- [x] Final Viewer evidence artifact `10304951419` (`sha256:d551006acffa260e8bbd83e25c2b156204a4391f1f9b1abcfc4e58aa0cc28e04`) was human-reviewed clean across desktop, 390px, disclosures, Source Fold temporal states, narrow comparison and reduced motion.
- [x] Presentation-only verifier migrations aligned stale pre-UI-076 locators with the approved composition while preserving product/security assertions; the final Lifecycle and Drag Drop gates executed fully and passed.
- [x] PR #200 squash-merged as `b672c711f885092c5e92c42824078e7bd5bc691e`.
- [x] Every workflow GitHub actually attached to merged `main` passed: Creative Iteration `34718303019`, Media Viewer Register Fold Visual `34718302986`, Engineering Quality `34718303036`, Upscale Viewer Visual `34718303044`, Image Upscale Integration `34718302998`, and UI Shell Validation `34718302987`.
- [ ] Production deployment remains separately explicit. Production is still source `0173c4c5ba08360b6352331118abc81978cfa774` / READY deployment `dpl_3Smw21pn4PPQ1DzN7aaWmTuuf991`; automatic Git → Vercel deployment remains disabled.

**Phase 25 boundary preserved:** `/library/[assetId]`, owner-scoped durable identity, native video, Favorite/Collections/Rename/Download/Delete, capability-derived continuation, Reuse settings, Compare source, Upscale 2×, routing, schema, provider/worker, R2/storage, auth/admission and deployment contracts remain product-truthful and unchanged.

"""
replace_once('docs/ui/UI_MIGRATION.md', '## Active full-product redesign roadmap — after Phase 24\n', phase25_migration + '## Active full-product redesign roadmap — after Phase 25\n')
replace_once('docs/ui/UI_MIGRATION.md', 'The coherent design authority carried forward is the current locked Lab Grid identity + approved Lab Matrix Landing + Clear Composer/UI-074 + Gallery Rail/UI-075.', 'The coherent design authority carried forward is the current locked Lab Grid identity + approved Lab Matrix Landing + Clear Composer/UI-074 + Gallery Rail/UI-075 + Media Register/Source Fold UI-076.')
replace_once('docs/ui/UI_MIGRATION.md', '- [ ] **Phase 25 Media Viewer redesign — ACTIVE R&D (#196).** Audit current desktop/390px image/video/Compare/Upscale/action states; build interaction references; explore 3+ same-family compositions; prototype signature Library→Viewer / Compare / Viewer→Create continuity; obtain explicit user approval before a production implementation contract.\n- [ ] **Phase 26 Activity redesign — ROADMAP ONLY.** Expand only after Phase 25 produces verified evidence.', '- [x] **Phase 25 Media Viewer redesign — USER-APPROVED / EXACT-HEAD VERIFIED / MERGED / MERGED-MAIN VERIFIED / NOT DEPLOYED.** UI-076 Media Register + Source Fold v0.2 is authoritative.\n- [ ] **Phase 26 Activity redesign — NEXT R&D SLICE.** Audit real lifecycle/history states and explore the same-family 2/4-expressiveness interaction language before any implementation contract or production code.')

replace_once('docs/ui/SCREEN_REGISTRY.md', '**Status:** APPROVED — Media Viewer base + Download + Rename + Favorites + Collections v0.1 / UI-032 + Delete v0.1 / UI-033 + Reuse Settings / Compare source / UI-056 + Image Upscale 2× / UI-058', '**Status:** APPROVED — UI-076 Media Register + Source Fold v0.2 with existing Download/Rename/Favorites/Collections/Delete, Reuse Settings/Compare source and Image Upscale 2× contracts')
replace_once('docs/ui/SCREEN_REGISTRY.md', '**Implementation:** `src/features/library/media-viewer.tsx`, `src/features/library/media-viewer-comparison.tsx`, `src/features/library/media-viewer-upscale-action.tsx`', '**Implementation:** `src/features/library/media-viewer.tsx`, `src/features/library/media-viewer-register.tsx`, `src/features/library/media-viewer-comparison.tsx`, `src/features/library/media-viewer-upscale-action.tsx`, `src/features/library/media-viewer.module.css`')
replace_once('docs/ui/SCREEN_REGISTRY.md', '**Design artifacts:** `design/penpot/media-viewer-v0.1.svg`, `design/penpot/media-viewer-v0.2-compare-source.md`', '**Design / implementation authority:** `docs/ui/MEDIA_VIEWER_REGISTER_FOLD_IMPLEMENTATION_CONTRACT.md`, UI-076, approved R&D issue #196 / exact design head `639aef25e57e166be8d8b3d226b3e83930e05a25`; historical behavior artifacts remain `design/penpot/media-viewer-v0.1.svg` and `design/penpot/media-viewer-v0.2-compare-source.md`')
replace_once('docs/ui/SCREEN_REGISTRY.md', '- responsive media-primary image/video presentation;\n- UI-069 requires', '- responsive registered media-primary image/video presentation under UI-076, with the durable asset itself acting as the workspace rather than content beside a permanent property sidebar;\n- capability-derived continuation is attached directly below the media stage in one Media Register; Prompt, Details and Manage are local disclosures from that same attached geometry; Favorite and Download are singular quick actions while Collections, Rename and permanent Delete live in Manage;\n- UI-069 requires')
replace_once('docs/ui/SCREEN_REGISTRY.md', '- Rename and Download remain side-by-side while the inline edit form expands beneath them on desktop/mobile;', '- UI-076 keeps Download as a singular quick action while Rename moves into the local Manage disclosure; rename form behavior and durable display-name semantics remain unchanged;')
replace_once('docs/ui/SCREEN_REGISTRY.md', '- UI-031 adds one full-width accessible `Favorite` / `Favorited` Viewer action above Rename/Download; it exposes `aria-pressed`, local saving/error feedback and an idempotent owner-scoped product mutation without changing continuation hierarchy;', '- UI-031 Favorite semantics remain unchanged; UI-076 presents Favorite as a singular accessible quick action with the same `aria-pressed`, local saving/error feedback and idempotent owner-scoped mutation;')
replace_once('docs/ui/SCREEN_REGISTRY.md', "- UI-032 adds one contextual `Collections` disclosure below Favorites; it lists only the verified owner's collections, supports create-and-add plus idempotent membership toggles with pressed state, and keeps Rename/Download plus continuation hierarchy unchanged.", "- UI-032 collection semantics remain unchanged; UI-076 places Collections inside Manage, still listing only the verified owner's collections with create-and-add plus idempotent membership toggles.")
replace_once('docs/ui/SCREEN_REGISTRY.md', '- UI-033 adds one visually secondary permanent `Delete` action beneath existing durable actions. Confirmation uses the maintained AlertDialog primitive; successful deletion tombstones first, removes collection/upload links, purges R2 content/thumbnail, preserves generation-history IDs and returns to Library. Tombstoned media is not reusable as a new generation input.', '- UI-033 permanent Delete semantics remain unchanged; UI-076 owns Delete inside Manage. Confirmation uses the maintained AlertDialog primitive; successful deletion tombstones first, removes collection/upload links, purges R2 content/thumbnail, preserves generation-history IDs and returns to Library. Tombstoned media is not reusable as a new generation input.')
replace_once('docs/ui/SCREEN_REGISTRY.md', '- UI-056 adds eligible successful-history `Reuse settings` and conditional `Compare source` without changing the default Viewer. Comparison appears only when the producing owner-scoped job resolves an active same-owner durable primary `media-asset`; temporary/deleted/foreign/no-source history fails closed. Wide layouts keep Result primary at roughly 60/40 with contained truthful media geometry; narrow layouts place a full-width Result first and a compact contextual Source card immediately below. Source exposes only `Open source` to its ordinary Viewer. Prompt, Details, Continue, Actions and result video playback controls remain result-owned; active comparison exits through `Close comparison`. No new route or durable comparison state is introduced.', '- UI-056 eligibility and ownership rules for `Reuse settings` and `Compare source` remain unchanged. UI-076 supersedes the old static comparison presentation with Result-primary **Source Fold**: desktop reallocates the registered stage while keeping Result materially primary; narrow layouts keep Result first and stack Source below. Temporary/deleted/foreign/no-source history still fails closed; Source exposes only `Open source`; result Prompt/Details/continuation/actions/native video remain result-owned; no new route or durable comparison state is introduced.')
phase25_screen_evidence = """**Phase 25 / UI-076 approval evidence:** user-approved R&D head `639aef25e57e166be8d8b3d226b3e83930e05a25`, run `34703774288`, artifact `10300577421` (`sha256:06cade2dc2e9ce51dc871971530fa9641a7c1ef0cc0271e19763fcebfa8ca2b0`). Contract PR #199 merged as `a5db944acdefad7b9fcbbedd9d6b521b5a28c576`. PR #200 definitive exact head `3e468ad0abd4f7b6645e86e298ce53a3a8ecf034` passed the complete affected acceptance set; dedicated Viewer run `34717466185` produced artifact `10304951419` (`sha256:d551006acffa260e8bbd83e25c2b156204a4391f1f9b1abcfc4e58aa0cc28e04`) and human review accepted desktop, 390px, disclosure, temporal Source Fold, narrow comparison and reduced-motion states. PR #200 squash-merged as `b672c711f885092c5e92c42824078e7bd5bc691e`; merged-main Creative Iteration `34718303019`, Viewer `34718302986`, Engineering `34718303036`, Upscale Viewer `34718303044`, Image Upscale `34718302998` and UI Shell `34718302987` all passed. Production remains unchanged until a separately authorized rollout.

"""
replace_once('docs/ui/SCREEN_REGISTRY.md', '**UI-056 Reuse / Compare approval evidence:**', phase25_screen_evidence + '**UI-056 Reuse / Compare approval evidence:**')
replace_once('docs/ui/SCREEN_REGISTRY.md', '**Do not change:** Provider/worker/R2 identity stays internal. Viewer continuation and recipe reuse remain capability/current-validation derived. Favorite/Collections/Download/Rename remain contextual product actions; UI-033 Delete follows its explicit tombstone/purge contract; UI-056 Source stays contextual and exposes only its ordinary Viewer link.', '**Do not change:** Provider/worker/R2 identity stays internal. Viewer continuation and recipe reuse remain capability/current-validation derived. Under UI-076 Favorite/Download remain quick actions and Collections/Rename/Delete remain Manage-owned; UI-033 Delete follows its explicit tombstone/purge contract; UI-056 Source stays contextual and exposes only its ordinary Viewer link.')

replace_once('docs/ui/COMPONENT_CATALOG.md', '**Origin:** RenderLab composition based on `design/penpot/media-viewer-v0.1.svg`, approved UI-056 comparison direction in `design/penpot/media-viewer-v0.2-compare-source.md`, and the UI-058 repository-backed `media-viewer-v0.3-upscale-2x` checkpoint', '**Origin:** RenderLab composition governed by UI-076 / `docs/ui/MEDIA_VIEWER_REGISTER_FOLD_IMPLEMENTATION_CONTRACT.md`, while preserving the approved UI-056 comparison product rules and UI-058 Upscale contract')
replace_once('docs/ui/COMPONENT_CATALOG.md', '**Purpose:** Contextual durable-media workspace: media-primary presentation, truthful metadata, capability-derived continuation and secondary durable asset actions.', '**Purpose:** Contextual durable-media workspace where the registered media object is the primary workspace, with attached continuation, local disclosures, truthful metadata and durable asset actions.')
replace_once('docs/ui/COMPONENT_CATALOG.md', '**Variants:** image/video; generated/uploaded metadata; optional dimensions/duration; continuation actions when supported; Viewer-only Favorite, Collections, Download and Rename; approved UI-033 single-asset Delete; UI-056 successful-history Reuse Settings and conditional durable-source comparison; UI-058 server-eligible fixed 2× image continuation.', '**Variants:** image/video; generated/uploaded metadata; attached Media Register; Prompt/Details/Manage disclosures; Favorite/Download quick actions; Manage-owned Collections/Rename/Delete; capability-derived continuation; UI-076 Result-primary Source Fold; UI-058 server-eligible fixed 2× image continuation.')
replace_once('docs/ui/COMPONENT_CATALOG.md', '**Dependencies:** Next.js Link, maintained Button/Alert/AlertDialog/Spinner primitives, Lucide React, `PublicMediaAsset`, shared continuation capabilities, product media/collection/Upscale routes, feature-owned `MediaViewerComparison`, `MediaViewerUpscaleAction`, `MediaViewerActions` and `MediaViewerCollections`.', '**Dependencies:** Next.js Link, maintained Button/Alert/AlertDialog/Spinner primitives, Lucide React, Motion for React/CSS for bounded Viewer transitions, `PublicMediaAsset`, shared continuation capabilities, product media/collection/Upscale routes, feature-owned `MediaViewerRegister`, `MediaViewerComparison`, `MediaViewerUpscaleAction`, `MediaViewerActions` and `MediaViewerCollections`.')
replace_once('docs/ui/COMPONENT_CATALOG.md', '**Notes:** Base generated-media Viewer/continuation passed `33034606396`; Download PR #11; Rename PR #12; Favorites PR #23.', '**Notes:** UI-076 Phase 25 is the current composition authority. Exact implementation head `3e468ad0abd4f7b6645e86e298ce53a3a8ecf034` passed the complete acceptance set; dedicated Viewer run `34717466185` produced artifact `10304951419` (`sha256:d551006acffa260e8bbd83e25c2b156204a4391f1f9b1abcfc4e58aa0cc28e04`), reviewed clean across desktop/390px/temporal/reduced-motion states. PR #200 merged as `b672c711f885092c5e92c42824078e7bd5bc691e`, and all six attached merged-main workflows passed. Historical behavior evidence remains: base generated-media Viewer/continuation `33034606396`; Download PR #11; Rename PR #12; Favorites PR #23.')
register_component = """### MediaViewerRegister
**Status:** APPROVED
**Source:** `src/features/library/media-viewer-register.tsx`
**Origin:** UI-076 Media Register + Source Fold v0.2 feature-local composition using maintained primitives and existing capability-derived Viewer actions.
**Purpose:** Attach continuation actions and local Prompt/Details/Manage disclosure ownership directly beneath the registered media stage without reintroducing a permanent property sidebar.
**Used by:** `MediaViewer` only.
**Dependencies:** current server-derived continuation capabilities, `MediaViewerActions`, `MediaViewerUpscaleAction`, maintained Button/disclosure mechanics and Viewer-local presentation state.
**Reuse rules:** Keep it Viewer-owned. Preserve server/capability truth, stable stage geometry, keyboard/touch reachability and reduced-motion equivalence; ordinary action behavior stays in the existing feature components/product routes.
**Do not:** Turn the register into global shell chrome, a generic property inspector, a client capability registry, a second media state store or a place to expose provider/worker/storage identity.
**Notes:** Approved under UI-076. Exact-head Viewer evidence `34717466185` / artifact `10304951419` verified default/disclosure states, Source Fold continuity, narrow composition and reduced motion; PR #200 merged as `b672c711f885092c5e92c42824078e7bd5bc691e`.

"""
replace_once('docs/ui/COMPONENT_CATALOG.md', '### MediaViewerUpscaleAction\n', register_component + '### MediaViewerUpscaleAction\n')
replace_once('docs/ui/COMPONENT_CATALOG.md', '**Origin:** RenderLab feature-local composition using maintained Button, Next.js Link and native image/video media elements under UI-056.\n**Purpose:** Progressive Source/Result comparison for an eligible generated Edit/Animate result while keeping the ordinary Viewer unchanged by default and preserving Result as the primary media/task surface.', '**Origin:** RenderLab feature-local comparison semantics established by UI-056 and current Source Fold presentation governed by UI-076.\n**Purpose:** Progressive Result-primary Source Fold for an eligible generated result, preserving truthful source/result media and keeping Source contextual rather than creating a second management surface.')
replace_once('docs/ui/COMPONENT_CATALOG.md', '**Reuse rules:** Keep comparison eligibility server-derived and owner/current-state validated. Wide layout keeps Result primary; narrow layout keeps full-width Result first with a compact Source card. Source exposes only `Open source`; result Prompt/Details/Continue/Actions and native video controls stay outside/owned by the result Viewer.', '**Reuse rules:** Keep comparison eligibility server-derived and owner/current-state validated. Desktop reallocates the same registered stage with Result materially primary; narrow layout keeps full-width Result first and stacks Source below. Source exposes only `Open source`; result Prompt/Details/continuation/actions and native video controls remain result-owned. Reduced motion renders the complete settled relationship without spatial transforms.')
replace_once('docs/ui/COMPONENT_CATALOG.md', '**Notes:** UI-056 exact implementation head `4d1a495a8145238e1e78756c7b09cdbaee8d8115`; Creative Iteration `33964679539`; final artifact `9969057974` (`sha256:cc20206371324f0698433731294924105174943cc0176dfd4ce9264fee6e8df5`) reviewed clean across Image→Image and Image→Video desktop/narrow. No new generic primitive was introduced.', '**Notes:** UI-056 exact implementation head `4d1a495a8145238e1e78756c7b09cdbaee8d8115` established eligibility/ownership semantics. UI-076 exact implementation head `3e468ad0abd4f7b6645e86e298ce53a3a8ecf034` supersedes the old comparison presentation with Source Fold; Viewer artifact `10304951419` verifies t000/t060/t180/t360 progression, narrow Result→Source stacking and reduced motion. No new route, durable comparison state or generic primitive was introduced.')
replace_once('docs/ui/COMPONENT_CATALOG.md', '**Purpose:** Viewer-owned secondary action group for durable Favorite + Collections + Rename + Download plus approved UI-033 single-asset Delete, including local mutation/confirmation state and the feature-owned Collections composition.', '**Purpose:** Viewer-owned durable action composition under UI-076: Favorite and Download are singular quick actions; Collections, Rename and UI-033 permanent Delete are owned by the local Manage disclosure, with existing mutation/confirmation semantics preserved.')
replace_once('docs/ui/COMPONENT_CATALOG.md', '**Notes:** Favorite remains full-width above the action stack; Collections is contextual below it; Rename/Download remain paired. UI-033 places Delete below the existing action stack as a visually secondary destructive action.', '**Notes:** UI-076 supersedes the old vertical action-stack presentation: Favorite/Download are quick actions and Collections/Rename/Delete live in Manage; product semantics and server routes are unchanged. UI-033 destructive confirmation remains the maintained AlertDialog contract.')

replace_once('docs/ui/UI_DECISIONS.md', '**Status:** Accepted / user-approved design; implementation pending  ', '**Status:** Accepted / user-approved / implemented / verified / merged / merged-main verified  ')
implementation_close = """**Implementation closure:** The required implementation contract merged first in PR #199 as `a5db944acdefad7b9fcbbedd9d6b521b5a28c576`. PR #200 then implemented UI-076 at definitive exact head `3e468ad0abd4f7b6645e86e298ce53a3a8ecf034`; the complete exact-head acceptance set passed, including dedicated Viewer run `34717466185`. Final implementation artifact `10304951419` (`sha256:d551006acffa260e8bbd83e25c2b156204a4391f1f9b1abcfc4e58aa0cc28e04`) was human-reviewed clean across desktop, 390px, Prompt/Details/Manage states, t000/t060/t180/t360 Source Fold, narrow Result→Source comparison and reduced motion. PR #200 squash-merged as `b672c711f885092c5e92c42824078e7bd5bc691e`; every workflow GitHub actually attached to merged `main` passed: Creative Iteration `34718303019`, Media Viewer Register Fold Visual `34718302986`, Engineering Quality `34718303036`, Upscale Viewer Visual `34718303044`, Image Upscale Integration `34718302998`, and UI Shell Validation `34718302987`. Production deployment remains separately explicit and was not performed.

**Ongoing fidelity gate:** Functional QA and fidelity QA remain separate. Future Viewer changes still fail this decision if they materially revert to a sidebar/dashboard composition, flatten Source Fold into an unrelated card fade, duplicate action ownership, obscure native video controls, weaken owner/capability truth, or diverge from the accepted desktop/390px/temporal/reduced-motion evidence without a new explicit redesign decision."""
replace_once('docs/ui/UI_DECISIONS.md', '**Implementation gate:** `docs/ui/MEDIA_VIEWER_REGISTER_FOLD_IMPLEMENTATION_CONTRACT.md` must be merged before production Viewer code changes. Functional QA and fidelity QA remain separate: build/tests may pass while the implementation still fails if it materially reverts to a sidebar/dashboard composition, flattens Source Fold into an unrelated card fade, duplicates action ownership, obscures native video controls, or diverges from the accepted desktop/390px/temporal/reduced-motion evidence. Production deployment remains separately explicit.', implementation_close)

print('Phase 25 closure documentation replacements applied.')
